
[project]
name = "closure_collector"
version = "0.0.2"
description = "A generalized closure collection dictionary and toolset."
authors = [{ name = "Andy P Fundinger", email = "Andy@ciemaar.com" }]
requires-python = ">=3.15"
dependencies = [
    "PyYAML",
    "pydantic-settings",
    "click",
    "glom"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "hypothesis==6.126.0",
    "pytest-cov==6.3.0",
    "coverage==7.5.0",
    "ruff",
    "mypy",
    "mdformat",
    "tox"
]
test = [
    "pytest",
    "hypothesis==6.126.0",
    "pytest-cov==6.3.0",
    "coverage==7.5.0"
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"



[tool.pytest.ini_options]
addopts = "--cov=src --cov-branch --cov-report=term-missing"
testpaths = ["test"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.ruff]
line-length = 160
src = ["src", "test"]
exclude = ["src/**/*.py", "test/**/*.py"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP"]
ignore = ["E731"]

[tool.ruff.lint.per-file-ignores]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.15"
warn_return_any = false
warn_unused_configs = true
exclude = ["src/.*", "test/.*"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.tox]
env_list = ["py315", "pyodide", "micropython", "lint", "type"]

[tool.tox.env_run_base]
extras = ["test"]
depends = ["clean"]
commands = [
    ["pytest", "--cov=src", "--cov-append", "--cov-report=term-missing", "--cov-branch"]
]


[tool.tox.env.pyodide]
extras = ["test"]
deps = ["pytest-pyodide"]
commands = [
    ["pytest", "test/", "--run-in-pyodide"]
]

[tool.tox.env.micropython]
skip_install = true
allowlist_externals = ["micropython", "python3"]
commands = [
    ["python3", "run_micropython_tests.py"]
]

[tool.tox.env.report]
deps = ["coverage==7.5.0"]
skip_install = true
commands = [
    ["coverage==7.5.0", "report"],
    ["coverage==7.5.0", "html"]
]
depends = ["py315"]

[tool.tox.env.clean]
deps = ["coverage==7.5.0"]
skip_install = true
commands = [
    ["coverage==7.5.0", "erase"]
]

[tool.tox.env.lint]
extras = ["dev"]
commands = [
    ["ruff", "check", "src", "test"],
    ["ruff", "format", "--check", "src", "test"]
]

[tool.tox.env.type]
extras = ["dev"]
commands = [
    ["mypy", "src", "test"]
]

[tool.tox.gh-actions]
python = """
    3.15: py315, type, lint
"""
