[tox]
envlist = py310, py311, py312, lint, type
isolated_build = True

[testenv]
deps =
    .[test]
commands =
    pytest

[testenv:lint]
deps =
    .[dev]
commands =
    ruff check .
    ruff format --check .

[testenv:type]
deps =
    .[dev]
    .[test]
commands =
    ty check . --exclude "Lightning\ Talk.ipynb" --exclude examples --exclude setup.py
