[tox]
envlist = py310, py311, py312, lint, type
isolated_build = True

[testenv]
deps =
    .[test]
commands =
    pytest

[testenv:lint]
deps =
    .[dev]
allowlist_externals = mdformat
commands =
    ruff check .
    ruff format --check .
    mdformat --check .

[testenv:type]
deps =
    .[dev]
    .[test]
commands =
    pyright .
